### ISSUE TITLE
Promise ist im Internet Explorer nicht unterstützt 

### ISSUE THREAD

**Issue by FrankBuchholz** [FrankBuchholz/EEP_convert_anl3_file#10]
Könnte man, wenn Promise undefined ist, eine dummy Definition von Promise nutzen, die einfach synchron weitermacht? Dann gibt es zwar keinen Ladebalken, aber man könnte auf das Einbinden einer weiteren externen Libary verzichten.

http://javascriptkit.com/javatutors/javascriptpromises.shtml

**Comment by campersau** [comment]
Das ist aber nicht das einzige Problem. Wenn wir den Internet Explorer 11 unterstützen wollen dann muss auch auf die folgenden Dinge verzichtet werden:

- [`for (const ... of ...)` Schleifen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility)
- [``` `` ``` Template Literale](https://caniuse.com/#feat=template-literals)

Soll ich das umbauen?

**Comment by FrankBuchholz** [comment]
Nein!

Schönen Gruß / Kind regards
Frank Buchholz
________________________________
Von: campersau <notifications@github.com>
Gesendet: Wednesday, August 14, 2019 8:15:21 PM
An: FrankBuchholz/EEP_convert_anl3_file <EEP_convert_anl3_file@noreply.github.com>
Cc: Frank Buchholz <frank.buchholz@web.de>; Author <author@noreply.github.com>
Betreff: Re: [FrankBuchholz/EEP_convert_anl3_file] Promise ist im Internet Explorer nicht unterstützt (#10)


Das ist aber nicht das einzige Problem. Wenn wir den Internet Explorer 11 unterstützen wollen dann muss auch auf die folgenden Dinge verzichtet werden:

  *   for (const ... of ...) Schleifen<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility>
  *   `` Template Literale<https://caniuse.com/#feat=template-literals>

Soll ich das umbauen?
