### ISSUE TITLE
Missing Color Picker Translations

### ISSUE THREAD

**Issue by campersau** [FrankBuchholz/EEP_convert_anl3_file#27]
https://github.com/FrankBuchholz/EEP_convert_anl3_file/blob/fea4fc2e051932c1f6c69db0d3bc345cb7eb42cf/EEP_Gleisplan.html#L5778

---

https://github.com/FrankBuchholz/EEP_convert_anl3_file/blob/fea4fc2e051932c1f6c69db0d3bc345cb7eb42cf/EEP_Gleisplan.html#L5709-L5735

**Comment by FrankBuchholz** [comment]
Es gibt noch vieles mehr zu übersetzen....
Bin also noch mittendrin.

Ich nutze 2 Systeme:
html: inline-translation innerhalb html via CSS (außer da wo es  nicht klappt wie z.B. bei options)
JavaScript: funktionsbasiert mit Ersatzsprache bei fehlender Übersetzung (Besonderheit: ich möchte die Texte in verschiedenen Sprachen nebeneinander sehen, um den Übersetzungsprozess zu erleichtern. Andere Frameworks setzen dagegen darauf, dass die Sprachdateien voneinander getrennt sind)

**Comment by FrankBuchholz** [comment]
Nun sollte Dank [Messina](https://www.eepforum.de/user/3932-messina/) alles übersetzt sein. 

Einschränkungen: 
- Das Programm merkt sich noch nicht die Sprachauswahl. Das rüste ist später nach.
- Die Signalstellungen, die auf dem Detail-Popup zu Signalen angezeigt werden, entnehme ich per separatem [Programm](https://frankbuchholz.github.io/EEP_convert_anl3_file/EEP_Signale.html) automatisch aus den .ini-Dateien der Signale. Dieses Programm liest z.Z. DE mit Ersatzsprache EN und speichert nur genau einen Text. Das Programm muss ich also auch irgendwann umbauen.
- Das [Invertarprogramm ](https://frankbuchholz.github.io/EEP_convert_anl3_file/EEP_Inventar.html) ist noch nicht übersetzt.

**Comment by FrankBuchholz** [comment]
- Übersetzung in English und Französisch abgeschlossen.
- Sprachauswahl wird in localStorage gespeichert.

**Comment by FrankBuchholz** [comment]
Das Inventarprogramm ist jetzt ebenfalls übersetzt.

**Comment by FrankBuchholz** [comment]
Die Signalstellungen aus den ini-Dateien werden jetzt - soweit vorhanden - in allen 3 Sprachen verwendet.
